package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InfluenceurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfluenceurAllPropertiesEquals(Influenceur expected, Influenceur actual) {
        assertInfluenceurAutoGeneratedPropertiesEquals(expected, actual);
        assertInfluenceurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfluenceurAllUpdatablePropertiesEquals(Influenceur expected, Influenceur actual) {
        assertInfluenceurUpdatableFieldsEquals(expected, actual);
        assertInfluenceurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfluenceurAutoGeneratedPropertiesEquals(Influenceur expected, Influenceur actual) {
        assertThat(actual)
            .as("Verify Influenceur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfluenceurUpdatableFieldsEquals(Influenceur expected, Influenceur actual) {
        assertThat(actual)
            .as("Verify Influenceur relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getPhotoUrl()).as("check photoUrl").isEqualTo(expected.getPhotoUrl()))
            .satisfies(a -> assertThat(a.getBio()).as("check bio").isEqualTo(expected.getBio()))
            .satisfies(a -> assertThat(a.getPlateforme()).as("check plateforme").isEqualTo(expected.getPlateforme()))
            .satisfies(a -> assertThat(a.getCategorie()).as("check categorie").isEqualTo(expected.getCategorie()))
            .satisfies(a -> assertThat(a.getScoreGlobal()).as("check scoreGlobal").isEqualTo(expected.getScoreGlobal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInfluenceurUpdatableRelationshipsEquals(Influenceur expected, Influenceur actual) {
        // empty method
    }
}
