package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScoreSentimentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreSentimentAllPropertiesEquals(ScoreSentiment expected, ScoreSentiment actual) {
        assertScoreSentimentAutoGeneratedPropertiesEquals(expected, actual);
        assertScoreSentimentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreSentimentAllUpdatablePropertiesEquals(ScoreSentiment expected, ScoreSentiment actual) {
        assertScoreSentimentUpdatableFieldsEquals(expected, actual);
        assertScoreSentimentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreSentimentAutoGeneratedPropertiesEquals(ScoreSentiment expected, ScoreSentiment actual) {
        assertThat(actual)
            .as("Verify ScoreSentiment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreSentimentUpdatableFieldsEquals(ScoreSentiment expected, ScoreSentiment actual) {
        assertThat(actual)
            .as("Verify ScoreSentiment relevant properties")
            .satisfies(a -> assertThat(a.getRatioPositif()).as("check ratioPositif").isEqualTo(expected.getRatioPositif()))
            .satisfies(a -> assertThat(a.getRatioNegatif()).as("check ratioNegatif").isEqualTo(expected.getRatioNegatif()))
            .satisfies(a -> assertThat(a.getRatioNeutre()).as("check ratioNeutre").isEqualTo(expected.getRatioNeutre()))
            .satisfies(a -> assertThat(a.getScoreSentiment()).as("check scoreSentiment").isEqualTo(expected.getScoreSentiment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreSentimentUpdatableRelationshipsEquals(ScoreSentiment expected, ScoreSentiment actual) {
        assertThat(actual)
            .as("Verify ScoreSentiment relationships")
            .satisfies(a -> assertThat(a.getInfluenceur()).as("check influenceur").isEqualTo(expected.getInfluenceur()));
    }
}
