package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScoreReachAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreReachAllPropertiesEquals(ScoreReach expected, ScoreReach actual) {
        assertScoreReachAutoGeneratedPropertiesEquals(expected, actual);
        assertScoreReachAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreReachAllUpdatablePropertiesEquals(ScoreReach expected, ScoreReach actual) {
        assertScoreReachUpdatableFieldsEquals(expected, actual);
        assertScoreReachUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreReachAutoGeneratedPropertiesEquals(ScoreReach expected, ScoreReach actual) {
        assertThat(actual)
            .as("Verify ScoreReach auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreReachUpdatableFieldsEquals(ScoreReach expected, ScoreReach actual) {
        assertThat(actual)
            .as("Verify ScoreReach relevant properties")
            .satisfies(a -> assertThat(a.getNbFollowers()).as("check nbFollowers").isEqualTo(expected.getNbFollowers()))
            .satisfies(a -> assertThat(a.getEngagementRate()).as("check engagementRate").isEqualTo(expected.getEngagementRate()))
            .satisfies(a -> assertThat(a.getReachEstime()).as("check reachEstime").isEqualTo(expected.getReachEstime()))
            .satisfies(a -> assertThat(a.getScoreReach()).as("check scoreReach").isEqualTo(expected.getScoreReach()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScoreReachUpdatableRelationshipsEquals(ScoreReach expected, ScoreReach actual) {
        assertThat(actual)
            .as("Verify ScoreReach relationships")
            .satisfies(a -> assertThat(a.getInfluenceur()).as("check influenceur").isEqualTo(expected.getInfluenceur()));
    }
}
